#!/usr/bin/env node
// Interactive first-time setup for Notifyer. Run with `npm run setup` (or
// `node setup.js` directly). Walks through the required and recommended
// environment variables, lets you opt into each platform integration one at
// a time, and writes the result to a .env file - so you don't have to read
// SELF_HOSTING.md front to back before your first successful boot.
//
// This only writes .env; it doesn't install dependencies, create your
// Discord application, or start the bot. Run `npm install` and
// `node index.js` (or `npm start`) on whichever branch you checked out
// yourself afterward.

const fs = require('fs');
const path = require('path');
const readline = require('readline/promises');
const { stdin, stdout } = require('process');

const ENV_PATH = path.join(__dirname, '.env');

async function main() {
    const rl = readline.createInterface({ input: stdin, output: stdout });
    const ask = async (question, { required = false, default: def = '' } = {}) => {
        while (true) {
            const suffix = def ? ` [${def}]` : '';
            const answer = (await rl.question(`${question}${suffix}: `)).trim();
            if (answer) return answer;
            if (def) return def;
            if (!required) return '';
            console.log('  This one is required - please enter a value.');
        }
    };
    const askYesNo = async (question, defaultYes = false) => {
        const suffix = defaultYes ? ' (Y/n)' : ' (y/N)';
        const answer = (await rl.question(`${question}${suffix}: `)).trim().toLowerCase();
        if (!answer) return defaultYes;
        return answer.startsWith('y');
    };

    console.log('--- Notifyer setup ---');
    console.log("This writes a .env file. It won't install dependencies or start the bot.\n");

    if (fs.existsSync(ENV_PATH)) {
        const overwrite = await askYesNo('.env already exists here - overwrite it?', false);
        if (!overwrite) {
            console.log('Leaving the existing .env untouched. Exiting.');
            rl.close();
            return;
        }
    }

    const env = {};

    console.log('\n[Required]');
    env.DISCORD_TOKEN = await ask('Discord bot token (from the Developer Portal)', { required: true });
    env.DATABASE_URL = await ask('Postgres connection string (postgres://user:pass@host:port/db)', { required: true });

    console.log('\n[Strongly recommended]');
    env.PUBLIC_BASE_URL = await ask('Public URL this bot will be reachable at (e.g. https://yourbot.onrender.com, blank to skip for now)');
    env.BOT_OWNER_ID = await ask('Your Discord user ID (gates owner-only debug commands, blank to skip)');
    env.PORT = await ask('Port for the built-in HTTP server', { default: '3000' });

    console.log('\n[Platform integrations - each is independently optional]');

    if (await askYesNo('Enable Twitch tracking?')) {
        env.TWITCH_CLIENT_ID = await ask('  Twitch client ID', { required: true });
        env.TWITCH_CLIENT_SECRET = await ask('  Twitch client secret', { required: true });
    }
    if (await askYesNo('Enable Kick tracking?')) {
        env.KICK_CLIENT_ID = await ask('  Kick client ID', { required: true });
        env.KICK_CLIENT_SECRET = await ask('  Kick client secret', { required: true });
    }
    if (await askYesNo('Enable YouTube tracking? (beta build only)')) {
        env.YOUTUBE_API_KEY = await ask('  YouTube Data API v3 key', { required: true });
    }
    if (await askYesNo('Enable Instagram OAuth linking? (beta build only, requires your own Meta app review)')) {
        env.INSTAGRAM_APP_ID = await ask('  Instagram/Meta app ID', { required: true });
        env.INSTAGRAM_APP_SECRET = await ask('  Instagram/Meta app secret', { required: true });
        if (!env.PUBLIC_BASE_URL) console.log('  Note: Instagram OAuth needs PUBLIC_BASE_URL set above to actually work.');
    }
    if (await askYesNo('Enable TikTok OAuth linking? (beta build only, requires your own TikTok app review)')) {
        env.TIKTOK_CLIENT_KEY = await ask('  TikTok client key', { required: true });
        env.TIKTOK_CLIENT_SECRET = await ask('  TikTok client secret', { required: true });
        if (!env.PUBLIC_BASE_URL) console.log('  Note: TikTok OAuth needs PUBLIC_BASE_URL set above to actually work.');
    }

    const lines = ['# Generated by setup.js on ' + new Date().toISOString()];
    for (const [key, value] of Object.entries(env)) {
        if (value) lines.push(`${key}=${value}`);
    }
    // 0600: this file holds the bot token and OAuth secrets, so keep it private to the owner.
    fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n', { mode: 0o600 });
    try { fs.chmodSync(ENV_PATH, 0o600); } catch { /* already-existing file on a filesystem without modes (e.g. Windows) */ }
    console.log(`\nWrote ${ENV_PATH}`);

    // A standard Discord bot token's first '.'-separated segment is the bot's
    // user ID, base64-encoded - which is also its application/client ID for
    // ordinary bots. Decoding it here just saves a trip to the Developer
    // Portal to build an invite link by hand.
    let clientId = null;
    try {
        const first = env.DISCORD_TOKEN.split('.')[0];
        const decoded = Buffer.from(first, 'base64').toString('utf8');
        if (/^\d+$/.test(decoded)) clientId = decoded;
    } catch { /* fall through to the manual-invite message below */ }

    console.log('\n[Next steps]');
    console.log('  1. npm install');
    console.log('  2. node index.js   (or npm start)');
    console.log('     On the main branch this is the release build (YouTube, Twitch, Kick, Twitter/X);');
    console.log('     on the Beta branch it also adds Instagram/TikTok.');
    if (clientId) {
        const permissions = 1024 /* View Channel */ + 2048 /* Send Messages */ + 16384 /* Embed Links */ + 262144 /* Use External Emojis */;
        console.log(`  3. Invite the bot to a server:\n     https://discord.com/api/oauth2/authorize?client_id=${clientId}&permissions=${permissions}&scope=bot%20applications.commands`);
    } else {
        console.log("  3. Invite the bot from the Developer Portal's OAuth2 URL Generator (bot + applications.commands scopes).");
    }
    console.log('  Slash commands register globally on first boot, which can take up to an hour to show up in Discord.');

    rl.close();
}

main().catch(e => {
    console.error('Setup failed:', e.message);
    process.exit(1);
});
